#!/usr/bin/env bash
# send files to remote server

file=$1
ip=$2
user=$3
id_file=$4

if [ -z "$file" ] && [ -z "$ip" ] && [ -z "$user" ] && [ -z "$id_file" ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i "$id_file" "$file" "$user@$ip:~"
fi
